{"Live" ":ableton:"
 "Adobe Bridge" ":adobe_bridge:"
 "Affinity Designer" ":affinity_designer:"
 "Affinity Designer 2" ":affinity_designer_2:"
 "Affinity Photo" ":affinity_photo:"
 "Affinity Photo 2" ":affinity_photo_2:"
 "Affinity Publisher" ":affinity_publisher:"
 "Affinity Publisher 2" ":affinity_publisher_2:"
 "Airmail" ":airmail:"
 "Alacritty" ":alacritty:"
 "Alfred" ":alfred:"
 "Android Messages" ":android_messages:"
 "Android Studio" ":android_studio:"
 "Anki" ":anki:"
 "Anytype" ":anytype:"
 "App Eraser" ":app_eraser:"
 "App Store" ":app_store:"
 "Arc" ":arc:"
 "Arduino" ":arduino:"
 "Arduino IDE" ":arduino:"
 "Atom" ":atom:"
 "Audacity" ":audacity:"
 "Bambu Studio" ":bambu_studio:"
 "MoneyMoney" ":bank:"
 "Battle.net" ":battle_net:"
 "Bear" ":bear:"
 "BetterTouchTool" ":bettertouchtool:"
 "Bilibili" ":bilibili:"
 "哔哩哔哩" ":bilibili:"
 "Bitwarden" ":bit_warden:"
 "Blender" ":blender:"
 "BluOS Controller" ":bluos_controller:"
 "Calibre" ":book:"
 "Brave Browser" ":brave_browser:"
 "BusyCal" ":busycal:"
 "Calculator" ":calculator:"
 "Calculette" ":calculator:"
 "Calendar" ":calendar:"
 "日历" ":calendar:"
 "Fantastical" ":calendar:"
 "Cron" ":calendar:"
 "Amie" ":calendar:"
 "Calendrier" ":calendar:"
 "Notion Calendar" ":calendar:"
 "Caprine" ":caprine:"
 "Amazon Chime" ":chime:"
 "Citrix Workspace" ":citrix:"
 "Citrix Viewer" ":citrix:"
 "Claude" ":claude:"
 "ClickUp" ":click_up:"
 "Code" ":code:"
 "Code - Insiders" ":code:"
 "Cold Turkey Blocker" ":cold_turkey_blocker:"
 "Color Picker" ":color_picker:"
 "数码测色计" ":color_picker:"
 "Copilot" ":copilot:"
 "CotEditor" ":coteditor:"
 "Creative Cloud" ":creative_cloud:"
 "Cursor" ":cursor:"
 "Cypress" ":cypress:"
 "DataGrip" ":datagrip:"
 "DataSpell" ":dataspell:"
 "DaVinci Resolve" ":davinciresolve:"
 "Deezer" ":deezer:"
 "Default" ":default:"
 "CleanMyMac X" ":desktop:"
 "DEVONthink 3" ":devonthink3:"
 "DingTalk" ":dingtalk:"
 "钉钉" ":dingtalk:"
 "阿里钉" ":dingtalk:"
 "Discord" ":discord:"
 "Discord Canary" ":discord:"
 "Discord PTB" ":discord:"
 "Docker" ":docker:"
 "Docker Desktop" ":docker:"
 "GrandTotal" ":dollar:"
 "Receipts" ":dollar:"
 "Double Commander" ":doublecmd:"
 "Drafts" ":drafts:"
 "draw.io" ":draw_io:"
 "Dropbox" ":dropbox:"
 "Element" ":element:"
 "Emacs" ":emacs:"
 "Evernote Legacy" ":evernote_legacy:"
 "FaceTime" ":face_time:"
 "FaceTime 通话" ":face_time:"
 "Figma" ":figma:"
 "Final Cut Pro" ":final_cut_pro:"
 "Finder" ":finder:"
 "访达" ":finder:"
 "Firefox" ":firefox:"
 "Firefox Developer Edition" ":firefox_developer_edition:"
 "Firefox Nightly" ":firefox_developer_edition:"
 "Folx" ":folx:"
 "Fork" ":fork:"
 "FreeTube" ":freetube:"
 "Fusion" ":fusion:"
 "System Preferences" ":gear:"
 "System Settings" ":gear:"
 "系统设置" ":gear:"
 "Réglages Système" ":gear:"
 "GitHub Desktop" ":git_hub:"
 "Godot" ":godot:"
 "GoLand" ":goland:"
 "Chromium" ":google_chrome:"
 "Google Chrome" ":google_chrome:"
 "Google Chrome Canary" ":google_chrome:"
 "Grammarly Editor" ":grammarly:"
 "Ghostty" "👻" ;; ":ghostty:"
 "Home Assistant" ":home_assistant:"
 "Hyper" ":hyper:"
 "IntelliJ IDEA" ":idea:"
 "IINA" ":iina:"
 "Adobe Illustrator" ":illustrator:"
 "Illustrator" ":illustrator:"
 "Adobe InDesign" ":indesign:"
 "InDesign" ":indesign:"
 "Inkdrop" ":inkdrop:"
 "Inkscape" ":inkscape:"
 "Insomnia" ":insomnia:"
 "Iris" ":iris:"
 "iTerm" ":iterm:"
 "iTerm2" ":iterm:"
 "Jellyfin Media Player" ":jellyfin:"
 "Joplin" ":joplin:"
 "카카오톡" ":kakaotalk:"
 "KakaoTalk" ":kakaotalk:"
 "Kakoune" ":kakoune:"
 "KeePassXC" ":kee_pass_x_c:"
 "Keyboard Maestro" ":keyboard_maestro:"
 "Keynote" ":keynote:"
 "Keynote 讲演" ":keynote:"
 "kitty" ":kitty:"
 "League of Legends" ":league_of_legends:"
 "LibreWolf" ":libre_wolf:"
 "Adobe Lightroom" ":lightroom:"
 "Lightroom Classic" ":lightroomclassic:"
 "LINE" ":line:"
 "Linear" ":linear:"
 "LM Studio" ":lm_studio:"
 "LocalSend" ":localsend:"
 "Logic Pro" ":logicpro:"
 "Logseq" ":logseq:"
 "Canary Mail" ":mail:"
 "HEY" ":mail:"
 "Mail" ":mail:"
 "Mailspring" ":mail:"
 "MailMate" ":mail:"
 "Superhuman" ":mail:"
 "Spark" ":mail:"
 "邮件" ":mail:"
 "MAMP" ":mamp:"
 "MAMP PRO" ":mamp:"
 "Maps" ":maps:"
 "Google Maps" ":maps:"
 "Marta" ":marta:"
 "Matlab" ":matlab:"
 "Mattermost" ":mattermost:"
 "Messages" ":messages:"
 "信息" ":messages:"
 "Nachrichten" ":messages:"
 "Messenger" ":messenger:"
 "Microsoft Edge" ":microsoft_edge:"
 "Microsoft Excel" ":microsoft_excel:"
 "Microsoft Outlook" ":microsoft_outlook:"
 "Microsoft PowerPoint" ":microsoft_power_point:"
 "Microsoft Remote Desktop" ":microsoft_remote_desktop:"
 "Microsoft Teams" ":microsoft_teams:"
 "Microsoft Teams (work or school)" ":microsoft_teams:"
 "Microsoft Word" ":microsoft_word:"
 "Min" ":min_browser:"
 "Miro" ":miro:"
 "MongoDB Compass" ":mongodb:"
 "mpv" ":mpv:"
 "Mullvad Browser" ":mullvad_browser:"
 "Music" ":music:"
 "音乐" ":music:"
 "Musique" ":music:"
 "Neovide" ":neovide:"
 "neovide" ":neovide:"
 "Neovim" ":neovim:"
 "neovim" ":neovim:"
 "nvim" ":neovim:"
 "网易云音乐" ":netease_music:"
 "Noodl" ":noodl:"
 "Noodl Editor" ":noodl:"
 "NordVPN" ":nord_vpn:"
 "Notability" ":notability:"
 "Notes" ":notes:"
 "备忘录" ":notes:"
 "Notion" ":notion:"
 "Nova" ":nova:"
 "Numbers" ":numbers:"
 "Numbers 表格" ":numbers:"
 "Obsidian" ":obsidian:"
 "OBS" ":obsstudio:"
 "OmniFocus" ":omni_focus:"
 "1Password" ":one_password:"
 "Open Video Downloader" ":open_video_downloader:"
 "ChatGPT" ":openai:"
 "OpenVPN Connect" ":openvpn_connect:"
 "Opera" ":opera:"
 "OrbStack" ":orbstack:"
 "OrcaSlicer" ":orcaslicer:"
 "Orion" ":orion:"
 "Orion RC" ":orion:"
 "Pages" ":pages:"
 "Pages 文稿" ":pages:"
 "Parallels Desktop" ":parallels:"
 "Parsec" ":parsec:"
 "Preview" ":pdf:"
 "预览" ":pdf:"
 "Skim" ":pdf:"
 "zathura" ":pdf:"
 "Aperçu" ":pdf:"
 "PDF Expert" ":pdf_expert:"
 "Pearcleaner" ":pearcleaner:"
 "Phoenix Slides" ":phoenix_slides:"
 "Adobe Photoshop" ":photoshop:"
 "PhpStorm" ":php_storm:"
 "Pi-hole Remote" ":pihole:"
 "Pine" ":pine:"
 "Plex" ":plex:"
 "Plexamp" ":plexamp:"
 "Podcasts" ":podcasts:"
 "播客" ":podcasts:"
 "PomoDone App" ":pomodone:"
 "Postman" ":postman:"
 "Proton Mail" ":proton_mail:"
 "Proton Mail Bridge" ":proton_mail:"
 "PrusaSlicer" ":prusaslicer:"
 "SuperSlicer" ":prusaslicer:"
 "PyCharm" ":pycharm:"
 "QQ" ":qq:"
 "QQ音乐" ":qqmusic:"
 "QQMusic" ":qqmusic:"
 "Quantumult X" ":quantumult_x:"
 "qutebrowser" ":qute_browser:"
 "Raindrop.io" ":raindrop_io:"
 "Reeder" ":reeder5:"
 "Reminders" ":reminders:"
 "提醒事项" ":reminders:"
 "Rappels" ":reminders:"
 "Replit" ":replit:"
 "Rider" ":rider:"
 "JetBrains Rider" ":rider:"
 "Rio" ":rio:"
 "Royal TSX" ":royaltsx:"
 "Safari" ":safari:"
 "Safari浏览器" ":safari:"
 "Safari Technology Preview" ":safari:"
 "Sequel Ace" ":sequel_ace:"
 "Sequel Pro" ":sequel_pro:"
 "Setapp" ":setapp:"
 "SF Symbols" ":sf_symbols:"
 "Signal" ":signal:"
 "sioyek" ":sioyek:"
 "Sketch" ":sketch:"
 "Skype" ":skype:"
 "Slack" ":slack:"
 "Spark Desktop" ":spark:"
 "Spotify" ":spotify:"
 "Spotlight" ":spotlight:"
 "Sublime Text" ":sublime_text:"
 "superProductivity" ":superproductivity:"
 "Tana" ":tana:"
 "TeamSpeak 3" ":team_speak:"
 "Telegram" ":telegram:"
 "Terminal" ":terminal:"
 "终端" ":terminal:"
 "Typora" ":text:"
 "Microsoft To Do" ":things:"
 "Things" ":things:"
 "Thunderbird" ":thunderbird:"
 "TickTick" ":tick_tick:"
 "TIDAL" ":tidal:"
 "Tiny RDM" ":tinyrdm:"
 "Todoist" ":todoist:"
 "Toggl Track" ":toggl_track:"
 "Tor Browser" ":tor_browser:"
 "Tower" ":tower:"
 "Transmit" ":transmit:"
 "Trello" ":trello:"
 "Tweetbot" ":twitter:"
 "Twitter" ":twitter:"
 "UTM" ":utm:"
 "MacVim" ":vim:"
 "Vim" ":vim:"
 "VimR" ":vim:"
 "Vivaldi" ":vivaldi:"
 "VLC" ":vlc:"
 "VMware Fusion" ":vmware_fusion:"
 "VSCodium" ":vscodium:"
 "Warp" ":warp:"
 "WebStorm" ":web_storm:"
 "微信" ":wechat:"
 "WeChat" ":wechat:"
 "企业微信" ":wecom:"
 "WeCom" ":wecom:"
 "WezTerm" ":wezterm:"
 "WhatsApp" ":whats_app:"
 "Xcode" ":xcode:"
 "Yandex Music" ":yandex_music:"
 "Yuque" ":yuque:"
 "语雀" ":yuque:"
 "Zed" ":zed:"
 "Zen Browser" ":zen_browser:"
 "Zeplin" ":zeplin:"
 "zoom.us" ":zoom:"
 "Zotero" ":zotero:"
 "Zulip" ":zulip:"}
