name: "Check flake outputs (no build)"
on:
  pull_request:
  push:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@v4
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    # Add `nix-on-droid` cache (for the static `proot`),
    # needed for `nix-on-droid` config evaluation
    - uses: cachix/cachix-action@v15
      with:
        name: nix-on-droid
    - uses: cachix/cachix-action@v15
      with:
        name: rix101
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: |
       # NOTE: `--no-build` to avoid building darwin stuff
       #       `--impure` because of `nix-on-droid`
       nix flake check --no-build --verbose --print-build-logs --impure
