name: "Publish every Git push to master to FlakeHub"
on:
  push:
    branches:
      - "master"
jobs:
  flakehub-publish:
    runs-on: "ubuntu-latest"
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "DeterminateSystems/nix-installer-action@v4"
      - uses: "DeterminateSystems/flakehub-push@v5"
        with:
          name: "reo101/rix101"
          rolling: true
          visibility: "public"
